[package]
name = "firezone-tunnel"
# mark:automatic-version
version = "1.0.0"
edition = "2021"

[dependencies]
secrecy = { workspace = true }
async-trait = { version = "0.1", default-features = false }
tokio = { version = "1.36", default-features = false, features = ["rt", "rt-multi-thread", "sync", "process"] }
thiserror = { version = "1.0", default-features = false }
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
futures =  { version = "0.3", default-features = false, features = ["std", "async-await", "executor"] }
futures-util =  { version = "0.3", default-features = false, features = ["std", "async-await", "async-await-macro"] }
tracing = { workspace = true }
bytes = { version = "1.4", default-features = false, features = ["std"] }
itertools = { version = "0.12", default-features = false, features = ["use_std"] }
connlib-shared = { workspace = true }
libc = { version = "0.2", default-features = false, features = ["std", "const-extern-fn", "extra_traits"] }
ip_network = { version = "0.4", default-features = false }
ip_network_table = { version = "0.2", default-features = false }
domain = { workspace = true }
boringtun = { workspace = true }
chrono = { workspace = true }
pnet_packet = { version = "0.34" }
futures-bounded = { workspace = true }
hickory-resolver = { workspace = true, features = ["tokio-runtime"] }
bimap = "0.6"
resolv-conf = "0.7.0"
socket2 = { version = "0.5" }
snownet = { workspace = true }
quinn-udp = { git = "https://github.com/quinn-rs/quinn", branch = "main"}
hex = "0.4.3"

# Needed for Android logging until tracing is fixed
log = "0.4"

[dev-dependencies]
anyhow = "1.0"
serde_json = "1.0"
tempfile = "3.10.0"

# Linux tunnel dependencies
[target.'cfg(target_os = "linux")'.dependencies]
netlink-packet-route = { version = "0.19", default-features = false }
netlink-packet-core = { version = "0.7", default-features = false }
rtnetlink = { workspace = true }
sd-notify = "0.4.1"

# Android tunnel dependencies
[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2"

# Windows tunnel dependencies
[target.'cfg(target_os = "windows")'.dependencies]
uuid = { version = "1.7.0", features = ["v4"] }
wintun = "0.4.0"

# Windows Win32 API
[target.'cfg(windows)'.dependencies.windows]
version = "0.52.0"
features = [
  "Win32_Foundation",
  "Win32_NetworkManagement_IpHelper",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
]
